version: '3.8'

services:
  validator:
    build: .
    container_name: subnet90-validator
    restart: unless-stopped
    environment:
      - WALLET_NAME=${WALLET_NAME}
      - HOTKEY_NAME=${HOTKEY_NAME:-default}
      - API_URL=${API_URL:-https://api.degenbrain.com}
      - NETWORK=${NETWORK:-finney}
      - SUBNET_UID=90
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - ./logs/validator:/app/logs
    networks:
      - subnet90
    ports:
      - "9944:9944"  # Bittensor
      - "9933:9933"  # RPC
      - "8091:8091"  # Axon
    command: python -m validator.main

  miner:
    build: .
    container_name: subnet90-miner
    restart: unless-stopped
    environment:
      - WALLET_NAME=${WALLET_NAME}
      - HOTKEY_NAME=${MINER_HOTKEY:-miner}
      - NETWORK=${NETWORK:-finney}
      - SUBNET_UID=90
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - ./logs/miner:/app/logs
    networks:
      - subnet90
    ports:
      - "8092:8091"  # Axon (different external port)
    command: python -m miner.main

  # Optional: Monitoring with Prometheus + Grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: subnet90-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - subnet90
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: subnet90-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - subnet90
    ports:
      - "3000:3000"

networks:
  subnet90:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: